### ISSUE TITLE
Filters for package label content

### ISSUE THREAD

**Issue by jmerilainen** [PostiDigital/woocommerce-shipping-plugin#16]
Hi,

Would it be possible to add a filter (`apply_filter`) to somewhere which could be used to modify content of the package label. 

For example we would like to not have weight and volume information in the label because some products doesn't have the correct information on WooCommerce's products.

I may be able to contribute the changes if this is something you would consider to merge.

**Comment by joosev** [comment]
This is a good issue. If you can do PR to https://github.com/Pakettikauppa/woo-pakettikauppa repository (against development barnch) so we can do proper testing etc.
