### ISSUE TITLE
Multiple shipping label labels for one package

### ISSUE THREAD

**Issue by GymEdgar** [PostiDigital/woocommerce-shipping-plugin#27]
Once order has been placed and shipping label is generated, it creates it three times, instead of one. This can be seen on Posti's Oma Posti service as well. 

This has previously worked and created one shipping label per order. I have also checked the backend for possible multiple parcel settings but I did not find anything.

Attached image:

![Posti](https://user-images.githubusercontent.com/102513094/160361629-e40dcef5-da0d-4d29-8f72-a79d4e29e00b.PNG)

Please assist.

**Comment by joosev** [comment]
Are you using automatically generated shipping labels? There is known to be an issue regarding that, that seems to happen from time to time in different webstores (we haven't been able to replicate it). We have build checks in there to prevent it but it still keeps happening for some reason. We will take a look.

**Comment by GymEdgar** [comment]
This happens when we click generate shipping label. It did not happen before when we were testing and using the plugin

**Comment by joosev** [comment]
Thank you for the extra information. We are looking if we can find out why this is happening.

**Comment by joosev** [comment]
Is this still an issue?
