### ISSUE TITLE
Test mode missing from the plugin

### ISSUE THREAD

**Issue by angryaxi** [PostiDigital/woocommerce-shipping-plugin#80]
Hi there,

I'm trying to replicate a bug in a local environment where in the shipping method goes missing on an order that failed during payment after which the payment method and shipping method was changed by the customer and the order was completed.

It seems that this plugin doesn't have a test mode that can be used for debugging.

There are some mentions of it in the source code, but it's non-functional and presumably disabled on purpose.

Are there any plans to reintroduce the ability to use the testing API? How do you test and debug this plugin currently?

**Comment by joosev** [comment]
Hi!

Unfortunately testing requires production credentials at the moment.

The test mode is a relic from older Posti system from where this plugin is based on (and the older system is already ramped down). We are bringing new test mode in the future but we have no schedule for it at the moment.
